### PR TITLE
Discussion about how to solve some timing issues

### PR DESCRIPTION
**Pull request by ghost**
Opened for discussion purposes.

### CODE REVIEW

**Comment by ghost** [comment]
https://github.com/Motiva-AI/clj-sqs-extended/pull/87 should make this obsolete, but I would like to hear your thoughts about making handler-side information available in the receive-loop.

**Comment by Quantisan** [comment]
@daisybytes what do you mean "making handler-side information available in the receive-loop"? Could you reference the specific code?

**Comment by ghost** [comment]
In the core ns `receive-loop` gets passed `number-of-handler-threads-running` and thereby knows how many handlers are currently running. Even though I would assume that the receiver and handler are (and maybe should be completely) independent from each other there might also be a situation where the receiver would want to know if there are still handlers running before completely shutting down. That was what came to my mind that day.

**Comment by ghost** [comment]
Closing this for now.

**Pull request closed without merging**
